// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/analisis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analisis">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/analisis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/cetak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cetak">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/cetak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/kelas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kelas">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/kelas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/management">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/mata-pelajaran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/mata-pelajaran">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/mata-pelajaran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/questions">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/bantuan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bantuan">> = Specific
  const handler = {} as typeof import("../../../src/app/bantuan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dokumentasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dokumentasi">> = Specific
  const handler = {} as typeof import("../../../src/app/dokumentasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/exam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exam">> = Specific
  const handler = {} as typeof import("../../../src/app/exam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/fitur-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fitur-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/fitur-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/integritas-ujian/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integritas-ujian">> = Specific
  const handler = {} as typeof import("../../../src/app/integritas-ujian/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/keamanan-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/keamanan-data">> = Specific
  const handler = {} as typeof import("../../../src/app/keamanan-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/kebijakan-privasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kebijakan-privasi">> = Specific
  const handler = {} as typeof import("../../../src/app/kebijakan-privasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../../src/app/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/panduan-guru/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panduan-guru">> = Specific
  const handler = {} as typeof import("../../../src/app/panduan-guru/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pin-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pin-verification">> = Specific
  const handler = {} as typeof import("../../../src/app/pin-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portal-siswa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal-siswa">> = Specific
  const handler = {} as typeof import("../../../src/app/portal-siswa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status">> = Specific
  const handler = {} as typeof import("../../../src/app/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/student-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student-status">> = Specific
  const handler = {} as typeof import("../../../src/app/student-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/syarat-ketentuan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/syarat-ketentuan">> = Specific
  const handler = {} as typeof import("../../../src/app/syarat-ketentuan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/[schoolId]/ai-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[schoolId]/ai-analysis">> = Specific
  const handler = {} as typeof import("../../../src/app/api/[schoolId]/ai-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/[schoolId]/proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[schoolId]/proxy">> = Specific
  const handler = {} as typeof import("../../../src/app/api/[schoolId]/proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-analysis">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/google-forms/[...segments]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-forms/[...segments]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/google-forms/[...segments]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy">> = Specific
  const handler = {} as typeof import("../../../src/app/api/proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
